### ISSUE TITLE
parsing a (very) huge debug log takes hours

### ISSUE THREAD

**Issue by paolostivanin** [bosh-tools/bosh-ext-cli#11]
I am trying to parse a 7M lines debug log, and after 17h the process is still ongoing. Cpu usage is 100%, RAM usage is 8 GB.
Is this expected? Can I help you debug this behavior somehow?

Thanks

**Comment by cppforlife** [comment]
@paolostivanin which git sha are you using?

**Comment by paolostivanin** [comment]
latest master cloned on Friday, 11th of August. The debug log is 
```
wc -l debug-1226589
6515621 debug-1226589
```

The process finished correctly though, it took ~34 hours:
```
wc -l out.log
587217 out.log
```
