### ISSUE TITLE
command to delete all orphaned disks on a director

### ISSUE THREAD

**Issue by cppforlife** [bosh-tools/bosh-ext-cli#21]
Previously submitted by @emalm

I've had to implement this myself with a shell pipeline for my BOSH-Lite, since a bunch of disks get orphaned when I occasionally have to delete my CF deployment there:

```
bosh -e "${BOSH_LITE_ENV_NAME}" disks --orphaned --json \
  | jq -r '.Tables[0].Rows[].disk_cid' \
  | xargs -n1 bosh -e "${BOSH_LITE_ENV_NAME}" -n delete-disk
```

The Diego team may also have had to do this to clear up disks on our scale benchmarking environment, which generates orphaned disks on every run when it creates and then deletes its deployments.

**Comment by tjvman** [comment]
`bosh clean-up --type=orphaned`?
